import type { AcademyLesson } from "@/features/help/types";

export const ACADEMY_LESSONS: AcademyLesson[] = [
  {
    lessonId: "welcome-postmotive",
    category: "Getting Started",
    title: "Welcome to PostMotive",
    summary: "Learn how the dashboard, guidance, and core workflow fit together before you start creating content.",
    durationMinutes: 6,
    difficulty: "Beginner",
    prerequisites: [],
    learningObjectives: [
      "Understand the main navigation",
      "Know where guidance and help live",
      "Recognize the content approval flow",
    ],
    steps: [
      { id: "welcome-1", title: "Open the dashboard", description: "Start at the Marketing Director dashboard to see priorities and system health.", route: "/" },
      { id: "welcome-2", title: "Review the Executive Brief", description: "Read the brief to understand what PostMotive sees as the most urgent work.", route: "/" },
      { id: "welcome-3", title: "Use Help & Academy", description: "Open the Help Center or Academy whenever you need a walkthrough or glossary definition.", route: "/help" },
    ],
    relatedRoutes: ["/", "/help", "/academy"],
  },
  {
    lessonId: "complete-business-setup",
    category: "Getting Started",
    title: "Complete Your Business Setup",
    summary: "Fill in the business profile so recommendations, compliance guidance, and brand voice have the right foundation.",
    durationMinutes: 8,
    difficulty: "Beginner",
    prerequisites: ["welcome-postmotive"],
    learningObjectives: ["Complete the workspace profile", "Choose the correct industry and compliance mode"],
    steps: [
      { id: "setup-1", title: "Open Business Setup", description: "Go to Business Setup and enter your business name, website, audience, and goals.", route: "/onboarding" },
      { id: "setup-2", title: "Set industry", description: "Choose the industry that best matches your business so compliance rules can adjust guidance.", route: "/onboarding" },
      { id: "setup-3", title: "Save and continue", description: "Save the profile before moving to content or integrations.", route: "/onboarding" },
    ],
    relatedRoutes: ["/onboarding"],
  },
  {
    lessonId: "upload-brand-assets",
    category: "Media Library",
    title: "Upload Your Logo and Brand Assets",
    summary: "Use the Media Library and Branding settings to prepare logos, product visuals, and reusable creative assets.",
    durationMinutes: 7,
    difficulty: "Beginner",
    prerequisites: ["complete-business-setup"],
    learningObjectives: ["Upload assets", "Organize folders", "Apply branding settings"],
    steps: [
      { id: "assets-1", title: "Open Media Library", description: "Upload logos, photos, and videos you expect to reuse.", route: "/media" },
      { id: "assets-2", title: "Create folders", description: "Group assets by campaign or purpose so the AI Studio stays organized.", route: "/media" },
      { id: "assets-3", title: "Set branding", description: "Add logo, color, and login branding details in Branding settings.", route: "/settings/branding" },
    ],
    relatedRoutes: ["/media", "/settings/branding"],
  },
  {
    lessonId: "connect-first-channel",
    category: "Integrations",
    title: "Connect Your First Marketing Channel",
    summary: "Connect TikTok or Amazon Ads so PostMotive can understand channel readiness and data coverage.",
    durationMinutes: 6,
    difficulty: "Beginner",
    prerequisites: ["complete-business-setup"],
    learningObjectives: ["Open the integrations overview", "Review permissions", "Check connection health"],
    steps: [
      { id: "connect-1", title: "Open Integrations", description: "Review the available provider cards and current health states.", route: "/integrations" },
      { id: "connect-2", title: "Choose a provider", description: "Open TikTok or Amazon Ads settings based on the channel you want to activate first.", route: "/settings/integrations/tiktok" },
      { id: "connect-3", title: "Verify health", description: "Return to the integrations overview and confirm the provider no longer needs reconnection.", route: "/integrations" },
    ],
    relatedRoutes: ["/integrations", "/settings/integrations/tiktok", "/settings/integrations/amazon-ads"],
  },
  {
    lessonId: "generate-first-plan",
    category: "Marketing Director",
    title: "Generate Your First Marketing Plan",
    summary: "Use the Marketing Director to turn a business request into a structured plan with recommended actions.",
    durationMinutes: 10,
    difficulty: "Beginner",
    prerequisites: ["complete-business-setup"],
    learningObjectives: ["Use the command center", "Review plan structure", "Understand approval boundaries"],
    steps: [
      { id: "plan-1", title: "Open the dashboard", description: "Start from the Marketing Director dashboard.", route: "/" },
      { id: "plan-2", title: "Submit a request", description: "Use the command center to ask for a plan tied to a campaign or business goal.", route: "/" },
      { id: "plan-3", title: "Review recommendations", description: "Check required approvals and recommended next steps before acting.", route: "/" },
    ],
    relatedRoutes: ["/"],
  },
  {
    lessonId: "generate-content-from-plan",
    category: "Content Studio",
    title: "Generate Content From a Plan",
    summary: "Move from campaign or director planning into the AI Studio and save usable drafts.",
    durationMinutes: 9,
    difficulty: "Beginner",
    prerequisites: ["generate-first-plan"],
    learningObjectives: ["Open AI Studio", "Create content", "Save usable drafts"],
    steps: [
      { id: "content-1", title: "Open AI Studio", description: "Use the Create content actions from campaigns or the dashboard.", route: "/studio" },
      { id: "content-2", title: "Generate a draft", description: "Describe your angle, channel, and objective clearly.", route: "/studio" },
      { id: "content-3", title: "Save to Content Library", description: "Keep the draft so it can move into review and scheduling.", route: "/media?tab=CONTENT_DRAFTS" },
    ],
    relatedRoutes: ["/studio", "/media?tab=CONTENT_DRAFTS"],
  },
  {
    lessonId: "review-and-approve-content",
    category: "Content Studio",
    title: "Review and Approve Content",
    summary: "Learn how drafts move from creation to approval and then into the publishing flow.",
    durationMinutes: 7,
    difficulty: "Beginner",
    prerequisites: ["generate-content-from-plan"],
    learningObjectives: ["Review drafts", "Understand approval states", "Move work forward safely"],
    steps: [
      { id: "approve-1", title: "Open Content Library", description: "Choose the draft you want to review.", route: "/media?tab=CONTENT_DRAFTS" },
      { id: "approve-2", title: "Use the approval queue", description: "Open the approval center if the draft requires team review.", route: "/approvals" },
      { id: "approve-3", title: "Prepare for scheduling", description: "Once approved, move the draft into the calendar or publishing queue.", route: "/calendar" },
    ],
    relatedRoutes: ["/media?tab=CONTENT_DRAFTS", "/approvals", "/calendar"],
  },
  {
    lessonId: "schedule-first-post",
    category: "Scheduling",
    title: "Schedule Your First Post",
    summary: "Use the calendar to assign a time, channel, and final status for approved work.",
    durationMinutes: 6,
    difficulty: "Beginner",
    prerequisites: ["review-and-approve-content"],
    learningObjectives: ["Use the calendar", "Check queue state", "Confirm time and platform"],
    steps: [
      { id: "schedule-1", title: "Open Calendar", description: "Review scheduled content and choose a draft to place.", route: "/calendar" },
      { id: "schedule-2", title: "Pick date and channel", description: "Set the date, time, and connected platform.", route: "/calendar" },
      { id: "schedule-3", title: "Monitor publishing queue", description: "Watch the status after the item leaves the draft stage.", route: "/publishing-queue" },
    ],
    relatedRoutes: ["/calendar", "/publishing-queue"],
  },
  {
    lessonId: "understand-marketing-score",
    category: "Analytics",
    title: "Understand Marketing Score",
    summary: "See how the score reflects setup quality, activity, approvals, and connected data.",
    durationMinutes: 5,
    difficulty: "Beginner",
    prerequisites: ["welcome-postmotive"],
    learningObjectives: ["Read the score", "Use score drivers", "Understand why missing data matters"],
    steps: [
      { id: "score-1", title: "Open the dashboard", description: "Find the Marketing Score card and related confidence information.", route: "/" },
      { id: "score-2", title: "Review Data Coverage", description: "Check which sources are helping or limiting score confidence.", route: "/" },
      { id: "score-3", title: "Use related analytics", description: "Open analytics dashboards for deeper performance details.", route: "/analytics" },
    ],
    relatedRoutes: ["/", "/analytics"],
  },
  {
    lessonId: "understand-ai-confidence",
    category: "Advanced AI",
    title: "Understand AI Confidence",
    summary: "Learn what raises or lowers confidence in AI recommendations and drafts.",
    durationMinutes: 4,
    difficulty: "Intermediate",
    prerequisites: ["understand-marketing-score"],
    learningObjectives: ["Read confidence labels", "Know what missing data means", "Act on limited confidence"],
    steps: [
      { id: "confidence-1", title: "Look for confidence labels", description: "Review dashboard and recommendation areas where confidence is shown.", route: "/" },
      { id: "confidence-2", title: "Check integrations and assets", description: "Connect more data and upload assets to improve confidence.", route: "/integrations" },
      { id: "confidence-3", title: "Use approval gates", description: "Low confidence is a signal to review carefully before publishing.", route: "/approvals" },
    ],
    relatedRoutes: ["/", "/integrations", "/approvals"],
  },
  {
    lessonId: "connect-tiktok",
    category: "TikTok",
    title: "Connect TikTok",
    summary: "Set up TikTok OAuth, permissions, and publishing readiness using the current beta-safe workflow.",
    durationMinutes: 8,
    difficulty: "Intermediate",
    prerequisites: ["connect-first-channel"],
    learningObjectives: ["Understand permissions", "Know draft-vs-direct-post availability", "Check recent jobs"],
    steps: [
      { id: "tt-1", title: "Open TikTok settings", description: "Go to the TikTok settings page from Integrations.", route: "/settings/integrations/tiktok" },
      { id: "tt-2", title: "Connect and authorize", description: "Use the connect button and approve the required scopes.", route: "/settings/integrations/tiktok" },
      { id: "tt-3", title: "Review status and jobs", description: "Confirm token health, permissions, and any recent publish jobs.", route: "/settings/integrations/tiktok" },
    ],
    relatedRoutes: ["/settings/integrations/tiktok", "/integrations"],
  },
  {
    lessonId: "connect-amazon-ads",
    category: "Amazon",
    title: "Connect Amazon Ads",
    summary: "Review the current Amazon Ads connection experience and understand what is available today versus coming soon.",
    durationMinutes: 5,
    difficulty: "Intermediate",
    prerequisites: ["connect-first-channel"],
    learningObjectives: ["Understand the sandbox/live boundary", "Open the read-only dashboard", "Know current limitations"],
    steps: [
      { id: "amazon-1", title: "Open Amazon Ads settings", description: "Review the current connection surface and current status.", route: "/settings/integrations/amazon-ads" },
      { id: "amazon-2", title: "Open analytics", description: "Use the Amazon Ads analytics dashboard to inspect available insight flows.", route: "/analytics/amazon-ads" },
      { id: "amazon-3", title: "Track limitations honestly", description: "Treat any unsupported live capability as coming soon until the connection surface confirms otherwise.", route: "/integrations" },
    ],
    relatedRoutes: ["/settings/integrations/amazon-ads", "/analytics/amazon-ads", "/integrations"],
  },
  {
    lessonId: "use-advisor-mode-safely",
    category: "Marketing Director",
    title: "Use Advisor Mode Safely",
    summary: "Learn how to keep people in control while still benefiting from AI planning and suggestions.",
    durationMinutes: 5,
    difficulty: "Beginner",
    prerequisites: ["welcome-postmotive"],
    learningObjectives: ["Understand Advisor mode", "Know where approvals stay required", "Use safer next steps"],
    steps: [
      { id: "advisor-1", title: "Open Director settings", description: "Review operating mode and approval settings.", route: "/settings/marketing-director" },
      { id: "advisor-2", title: "Keep approvals enabled", description: "Confirm the settings that require human review before content or publishing actions continue.", route: "/settings/marketing-director" },
      { id: "advisor-3", title: "Use the dashboard brief", description: "Start from recommended actions instead of forcing fully automated steps.", route: "/" },
    ],
    relatedRoutes: ["/settings/marketing-director", "/"],
  },
  {
    lessonId: "manage-credits-and-billing",
    category: "Billing and Credits",
    title: "Manage Credits and Billing",
    summary: "Review plan, invoices, and credit balances so the workspace stays ready for AI and publishing work.",
    durationMinutes: 6,
    difficulty: "Beginner",
    prerequisites: ["welcome-postmotive"],
    learningObjectives: ["Review plan status", "Open the customer portal", "Understand credit categories"],
    steps: [
      { id: "billing-1", title: "Open Billing", description: "Review the current plan and latest invoices.", route: "/settings/billing" },
      { id: "billing-2", title: "Check credits", description: "Review AI, video, publishing, and analytics credit balances.", route: "/settings/billing" },
      { id: "billing-3", title: "Change plan or payment method", description: "Use Stripe checkout or the billing portal when ready.", route: "/settings/billing" },
    ],
    relatedRoutes: ["/settings/billing"],
  },
  {
    lessonId: "creator-marketing-intro",
    category: "Creator Hub",
    title: "Introduction to Creator Marketing",
    summary: "Learn how Creator Hub connects discovery, outreach, campaign execution, and approved UGC workflows.",
    durationMinutes: 7,
    difficulty: "Beginner",
    prerequisites: ["welcome-postmotive"],
    learningObjectives: ["Understand Creator Hub routes", "Know lifecycle stages", "Avoid unsupported assumptions"],
    steps: [
      { id: "creator-intro-1", title: "Open Creator Dashboard", description: "Review active campaigns, pending reviews, and recommended creator actions.", route: "/creators" },
      { id: "creator-intro-2", title: "Open Discover Creators", description: "See filterable creator profiles and match explanations.", route: "/creators/discover" },
      { id: "creator-intro-3", title: "Review Pipeline", description: "Track negotiation and production stages before content review.", route: "/creators/pipeline" },
    ],
    relatedRoutes: ["/creators", "/creators/discover", "/creators/pipeline"],
  },
  {
    lessonId: "creator-find-right-fit",
    category: "Creator Hub",
    title: "Finding the Right Creator",
    summary: "Use deterministic filters and match factors to shortlist creator candidates safely.",
    durationMinutes: 8,
    difficulty: "Beginner",
    prerequisites: ["creator-marketing-intro"],
    learningObjectives: ["Apply filters", "Interpret match reasons", "Review safety and availability"],
    steps: [
      { id: "creator-find-1", title: "Set discover filters", description: "Filter by platform, niche, location, and engagement thresholds.", route: "/creators/discover" },
      { id: "creator-find-2", title: "Open a creator profile", description: "Review audience summary, pricing range, and compatibility notes.", route: "/creators/discover" },
      { id: "creator-find-3", title: "Save candidates", description: "Save qualified creators and move them into pipeline stages.", route: "/creators/pipeline" },
    ],
    relatedRoutes: ["/creators/discover", "/creators/pipeline"],
  },
  {
    lessonId: "creator-outreach-management",
    category: "Creator Hub",
    title: "Managing Creator Outreach",
    summary: "Run creator outreach in stages with ownership, notes, and next-action follow-up dates.",
    durationMinutes: 7,
    difficulty: "Intermediate",
    prerequisites: ["creator-find-right-fit"],
    learningObjectives: ["Assign ownership", "Track next actions", "Manage negotiation transitions"],
    steps: [
      { id: "creator-outreach-1", title: "Open pipeline", description: "Filter by stage and owner to find outreach work.", route: "/creators/pipeline" },
      { id: "creator-outreach-2", title: "Set next action", description: "Add notes and follow-up timing for each creator.", route: "/creators/pipeline" },
      { id: "creator-outreach-3", title: "Attach to campaign", description: "Link qualified creators to campaign records before production starts.", route: "/creators/campaigns" },
    ],
    relatedRoutes: ["/creators/pipeline", "/creators/campaigns"],
  },
  {
    lessonId: "creator-campaign-builder",
    category: "Creator Hub",
    title: "Building a Creator Campaign",
    summary: "Use campaign builder fields for goals, budget, creators, deliverables, approvals, and tracking placeholders.",
    durationMinutes: 9,
    difficulty: "Intermediate",
    prerequisites: ["creator-outreach-management"],
    learningObjectives: ["Define campaign scope", "Assign creators and deliverables", "Set approval expectations"],
    steps: [
      { id: "creator-campaign-1", title: "Create campaign basics", description: "Set campaign name, goal, timeline, and budget.", route: "/creators/campaigns" },
      { id: "creator-campaign-2", title: "Select creators", description: "Add shortlisted creators and required platforms.", route: "/creators/campaigns" },
      { id: "creator-campaign-3", title: "Set approval and rights", description: "Capture approval rules and usage-rights notes before launch.", route: "/creators/campaigns" },
    ],
    relatedRoutes: ["/creators/campaigns"],
  },
  {
    lessonId: "creator-content-review",
    category: "Creator Hub",
    title: "Reviewing Creator Content",
    summary: "Process creator submissions with approve, reject, revision request, and comment actions.",
    durationMinutes: 6,
    difficulty: "Beginner",
    prerequisites: ["creator-campaign-builder"],
    learningObjectives: ["Review submission statuses", "Request revisions safely", "Move approved assets to library"],
    steps: [
      { id: "creator-review-1", title: "Open content review", description: "Check submitted and in-review assets.", route: "/creators/content-review" },
      { id: "creator-review-2", title: "Take review actions", description: "Approve, reject, request revision, or comment.", route: "/creators/content-review" },
      { id: "creator-review-3", title: "Save approved assets", description: "Move approved assets to UGC and Media Library workflows.", route: "/creators/ugc" },
    ],
    relatedRoutes: ["/creators/content-review", "/creators/ugc"],
  },
  {
    lessonId: "creator-roi-analysis",
    category: "Creator Hub",
    title: "Understanding Creator ROI",
    summary: "Read measured vs estimated creator performance metrics without overstating unsupported ROI values.",
    durationMinutes: 6,
    difficulty: "Intermediate",
    prerequisites: ["creator-content-review"],
    learningObjectives: ["Interpret measured labels", "Interpret estimated labels", "Avoid fabricated ROI assumptions"],
    steps: [
      { id: "creator-roi-1", title: "Open creator analytics", description: "Review campaign and creator leaderboard metrics.", route: "/creators/analytics" },
      { id: "creator-roi-2", title: "Compare labels", description: "Separate measured from estimated and demo values.", route: "/creators/analytics" },
      { id: "creator-roi-3", title: "Act on confidence", description: "Use measured metrics for decisions and treat demo values as simulation only.", route: "/creators/analytics" },
    ],
    relatedRoutes: ["/creators/analytics"],
  },
  {
    lessonId: "creator-usage-rights",
    category: "Creator Hub",
    title: "Managing Usage Rights",
    summary: "Track usage windows, approval state, and campaign reuse in the UGC library.",
    durationMinutes: 5,
    difficulty: "Beginner",
    prerequisites: ["creator-content-review"],
    learningObjectives: ["Filter by rights status", "Validate approval state", "Archive expired assets"],
    steps: [
      { id: "creator-rights-1", title: "Open UGC library", description: "Filter assets by creator, campaign, and platform.", route: "/creators/ugc" },
      { id: "creator-rights-2", title: "Check rights windows", description: "Review rights start and end dates before reuse.", route: "/creators/ugc" },
      { id: "creator-rights-3", title: "Archive expired assets", description: "Archive assets no longer covered by usage rights.", route: "/creators/ugc" },
    ],
    relatedRoutes: ["/creators/ugc"],
  },
  {
    lessonId: "read-executive-brief",
    category: "Marketing Director",
    title: "Read the Executive Brief",
    summary: "Use the daily brief to understand the most important next actions without digging through every page.",
    durationMinutes: 4,
    difficulty: "Beginner",
    prerequisites: ["welcome-postmotive"],
    learningObjectives: ["Understand urgency", "Review top actions", "Know when to open related pages"],
    steps: [
      { id: "brief-1", title: "Open dashboard", description: "Start from the Marketing Director dashboard.", route: "/" },
      { id: "brief-2", title: "Read urgency and top actions", description: "Use the brief to focus on what most needs attention.", route: "/" },
      { id: "brief-3", title: "Follow linked actions", description: "Open the related page directly from the suggested next step.", route: "/" },
    ],
    relatedRoutes: ["/"],
  },
];

export function getAcademyLesson(lessonId: string): AcademyLesson | null {
  return ACADEMY_LESSONS.find((lesson) => lesson.lessonId === lessonId) || null;
}
