import { HELP_TERM_REGISTRY } from "@/features/help/term-registry";
import type { PageHelpEntry } from "@/features/help/types";

function terms(...names: string[]) {
  return names
    .map((name) => HELP_TERM_REGISTRY.find((term) => term.term === name))
    .filter((item): item is NonNullable<typeof item> => Boolean(item));
}

export const PAGE_HELP_REGISTRY: PageHelpEntry[] = [
  {
    id: "help-center",
    route: "/help",
    title: "Help Center",
    shortDescription: "Search guidance, FAQs, page help, and academy links from one place.",
    purpose: "This page is the central guidance index for first-time users and beta testers.",
    whyItMatters: "It is the fastest recovery path when a user feels lost or needs a trustworthy next step.",
    recommendedFirstAction: "Search for the task or page you are trying to use, then open the matching guide or lesson.",
    estimatedTime: "1-3 minutes",
    quickStartSteps: [
      { id: "help-center-1", title: "Search the task", description: "Search by action, page name, or term such as connect TikTok or approve a post.", route: "/help" },
      { id: "help-center-2", title: "Open a guide or page", description: "Use the result that best matches the action you need to take now.", route: "/help" },
    ],
    tips: ["The Help Center favors documented product behavior over guesses or hidden capability assumptions."],
    terminology: terms("Marketing Score", "AI Confidence", "Approval"),
    commonQuestions: [{ question: "What should I search for?", answer: "Search the action you want to take, the page you are on, or the term you do not understand." }],
    relatedPages: [{ label: "Academy", href: "/academy" }, { label: "User Guide", href: "/help/user-guide" }],
  },
  {
    id: "academy",
    route: "/academy",
    title: "PostMotive Academy",
    shortDescription: "Written lessons that teach the main workflows without requiring video content to launch.",
    purpose: "This page groups guided lessons by category and tracks progress by workspace user.",
    whyItMatters: "Academy gives new users a structured learning path instead of forcing them to discover workflows through trial and error.",
    recommendedFirstAction: "Start with Welcome to PostMotive or the lesson closest to the workflow you are trying to complete now.",
    estimatedTime: "5-10 minutes",
    quickStartSteps: [
      { id: "academy-1", title: "Choose a lesson", description: "Start with Getting Started, Marketing Director, or Billing based on what is blocking you.", route: "/academy" },
      { id: "academy-2", title: "Mark progress", description: "Use Start lesson or Mark complete to track where you are in the learning flow.", route: "/academy" },
    ],
    tips: ["Lessons are written first so the Monday beta build can launch without waiting on videos."],
    terminology: terms("Advisor Mode", "Copilot Mode", "Publishing Queue"),
    commonQuestions: [{ question: "Do I need to finish every lesson?", answer: "No. Start with the lesson that helps you complete the task you are working on now." }],
    relatedPages: [{ label: "Help Center", href: "/help" }, { label: "Dashboard", href: "/" }],
  },
  {
    id: "dashboard",
    route: "/",
    title: "AI Marketing Director",
    shortDescription: "Your command center for priorities, recommendations, approvals, and publishing readiness.",
    purpose: "This dashboard combines the Executive Brief, priority actions, score, channel health, and AI execution signals into one place.",
    whyItMatters: "When you start here, you can act on the most important work without hunting through every page.",
    recommendedFirstAction: "Read the Executive Brief and open the first priority action that matches your current goal.",
    estimatedTime: "3-5 minutes",
    quickStartSteps: [
      { id: "dashboard-1", title: "Read the brief", description: "Review the Executive Brief to understand risks, opportunities, and urgency.", targetSelector: '[data-help="dashboard-executive-brief"]' },
      { id: "dashboard-2", title: "Use the command center", description: "Ask for a plan or next step when you want help turning goals into action.", targetSelector: '[data-help="dashboard-command-center"]' },
      { id: "dashboard-3", title: "Open a priority action", description: "Use the linked action to jump into approvals, content, calendar, or integrations.", targetSelector: '[data-help="dashboard-priority-actions"]' },
    ],
    tips: [
      "If AI Confidence looks limited, connect more channels or add assets before trusting aggressive recommendations.",
      "Priority Actions already map to real routes, so they are the fastest way to unblock work.",
    ],
    terminology: terms("Marketing Score", "AI Confidence", "Executive Brief", "Approval", "Publishing Queue", "Director Activity"),
    commonQuestions: [
      { question: "What should I do first on this page?", answer: "Start with the Executive Brief, then choose the top action or submit a request in the command center." },
      { question: "Why do some recommendations still need approval?", answer: "Safety settings, role rules, and current operating mode can require human approval before the next step runs." },
    ],
    relatedPages: [
      { label: "Business Setup", href: "/onboarding" },
      { label: "Content Library", href: "/content" },
      { label: "Integrations", href: "/integrations" },
    ],
    academyLessonId: "welcome-postmotive",
  },
  {
    id: "content-library",
    route: "/content",
    title: "Content Library",
    shortDescription: "Review, organize, and prepare drafts before they move into approval or scheduling.",
    purpose: "This page stores saved drafts, folders, media associations, and approval-ready content states.",
    whyItMatters: "Strong organization here makes review faster and prevents unfinished drafts from clogging the calendar.",
    recommendedFirstAction: "Open the newest draft or create a folder for the next campaign you are working on.",
    estimatedTime: "5-10 minutes",
    quickStartSteps: [
      { id: "content-start-1", title: "Generate or create content", description: "Create content in AI Studio, then return here to review the saved draft.", route: "/studio" },
      { id: "content-start-2", title: "Open the draft", description: "Select a draft from the list to inspect copy, media, and status.", targetSelector: '[data-help="content-draft-list"]' },
      { id: "content-start-3", title: "Edit and save", description: "Tighten the wording and save the draft once it is ready.", targetSelector: '[data-help="content-editor"]' },
      { id: "content-start-4", title: "Approve or schedule", description: "Use the schedule handoff when the draft is ready for the calendar.", targetSelector: '[data-help="content-schedule"]' },
    ],
    tips: [
      "Use folders by campaign or channel so future review sessions stay fast.",
      "A draft can be ready for approval even if you plan to schedule it later.",
    ],
    terminology: terms("Draft", "Approval", "Content Readiness", "Scheduled"),
    commonQuestions: [
      { question: "Why is awaiting approval showing under Draft?", answer: "This library stores approval-ready items inside the draft workflow until they are explicitly moved forward." },
      { question: "What happens after approval?", answer: "The next step is usually to open the Calendar or Approval Center and confirm timing or reviewer decisions." },
    ],
    relatedPages: [
      { label: "AI Studio", href: "/studio" },
      { label: "Approval Center", href: "/approvals" },
      { label: "Publishing Calendar", href: "/calendar" },
    ],
    academyLessonId: "review-and-approve-content",
  },
  {
    id: "media-library",
    route: "/media",
    title: "Media Library",
    shortDescription: "Upload and organize logos, photos, audio, and videos used across content and campaigns.",
    purpose: "This page stores workspace media, applies useful tags, and keeps reusable assets available for AI-assisted creation.",
    whyItMatters: "Well-labeled assets reduce rework and help the studio generate content that matches your brand faster.",
    recommendedFirstAction: "Upload your logo and the top assets you expect to use this week.",
    estimatedTime: "5-8 minutes",
    quickStartSteps: [
      { id: "media-start-1", title: "Create a folder", description: "Set up a folder for a campaign, brand kit, or product line.", targetSelector: '[data-help="media-folders"]' },
      { id: "media-start-2", title: "Upload brand assets", description: "Upload logos, product images, and short videos you want ready for creation.", targetSelector: '[data-help="media-upload-zone"]' },
      { id: "media-start-3", title: "Review tags", description: "Use tags to make logos, product photos, and social media assets easier to find.", targetSelector: '[data-help="media-asset-grid"]' },
      { id: "media-start-4", title: "Use them in AI Studio", description: "Once assets are uploaded, move into AI Studio to reference them in new drafts.", route: "/studio" },
    ],
    tips: [
      "Upload a logo before running first-time brand content so prompts can reference a real brand kit.",
      "Product-focused filenames automatically help tagging stay useful.",
    ],
    terminology: terms("Connected Channel", "Content Readiness"),
    commonQuestions: [
      { question: "Can I organize media before I generate content?", answer: "Yes. In fact, uploading and tagging assets first usually improves your first content session." },
      { question: "What if TikTok status fails to load here?", answer: "The library still works. TikTok status is only shown to help you know whether a channel is ready for publishing." },
    ],
    relatedPages: [
      { label: "Branding Settings", href: "/settings/branding" },
      { label: "AI Studio", href: "/studio" },
    ],
    academyLessonId: "upload-brand-assets",
  },
  {
    id: "calendar",
    route: "/calendar",
    title: "Publishing Calendar",
    shortDescription: "Schedule, review, and monitor approved content before it moves into publishing.",
    purpose: "This page combines scheduling, calendar visibility, publishing states, and post-performance follow-up.",
    whyItMatters: "It is the handoff point between creation and execution, so mistakes here directly affect timing and channel readiness.",
    recommendedFirstAction: "Load an approved draft or pick a scheduled item that still needs attention.",
    estimatedTime: "4-6 minutes",
    quickStartSteps: [
      { id: "calendar-start-1", title: "Review scheduled content", description: "Use the calendar grid to see what is already planned.", targetSelector: '[data-help="calendar-grid"]' },
      { id: "calendar-start-2", title: "Select a date", description: "Choose a date before assigning a draft to keep spacing and timing intentional.", targetSelector: '[data-help="calendar-grid"]' },
      { id: "calendar-start-3", title: "Add approved content", description: "Use a saved draft to fill the schedule form.", targetSelector: '[data-help="calendar-form"]' },
      { id: "calendar-start-4", title: "Confirm platform and time", description: "Check the channel, status, and scheduled time before you save.", targetSelector: '[data-help="calendar-form"]' },
    ],
    tips: [
      "The queue is different from the calendar: the calendar is planning, the queue is execution status.",
      "Use performance snapshots after publishing to teach the Knowledge Base what worked.",
    ],
    terminology: terms("Scheduled", "Publishing Queue", "Approval"),
    commonQuestions: [
      { question: "Why is a post still marked pending approval?", answer: "It likely has not cleared the final human review step yet, even if the schedule is drafted." },
      { question: "Where do I see posts already trying to publish?", answer: "Open Publishing Queue for the execution-stage view of scheduled work." },
    ],
    relatedPages: [
      { label: "Publishing Queue", href: "/publishing-queue" },
      { label: "Knowledge Base", href: "/knowledge" },
      { label: "Content Library", href: "/content" },
    ],
    academyLessonId: "schedule-first-post",
  },
  {
    id: "marketing-command-center",
    route: "/marketing",
    title: "Marketing",
    shortDescription: "Plan campaigns, define objectives, and move from strategy into content execution.",
    purpose: "This page is the campaign planning workspace where goals become concrete marketing plans.",
    whyItMatters: "A clear plan keeps AI output focused and improves approval and scheduling quality.",
    recommendedFirstAction: "Create your first campaign plan with one objective and one primary channel.",
    estimatedTime: "2-4 minutes",
    quickStartSteps: [
      { id: "marketing-start-1", title: "Create a campaign", description: "Save a campaign name, objective, and channel.", route: "/marketing" },
      { id: "marketing-start-2", title: "Review the campaign", description: "Confirm objective and timing before generating content.", route: "/marketing" },
      { id: "marketing-start-3", title: "Generate content", description: "Open AI Studio with campaign context and create a draft.", route: "/studio" },
    ],
    tips: [
      "Start small: one campaign with one clear objective is easier to execute.",
      "Use saved campaign context before generating content.",
    ],
    terminology: terms("Workflow", "Content Readiness", "Approval"),
    commonQuestions: [
      { question: "What should I do first?", answer: "Create a campaign plan with a clear objective and channel." },
      { question: "Where do I generate content?", answer: "After saving a campaign, open AI Studio to generate drafts." },
    ],
    relatedPages: [
      { label: "AI Studio", href: "/studio" },
      { label: "Content Library", href: "/content" },
    ],
    academyLessonId: "generate-first-plan",
  },
  {
    id: "campaigns",
    route: "/marketing/campaigns",
    title: "Campaigns",
    shortDescription: "Create and track campaign plans that feed objectives, channels, and content creation workflows.",
    purpose: "Campaigns turn high-level goals into a saved plan that the AI Studio and dashboard can follow.",
    whyItMatters: "Without a clear campaign plan, content generation becomes harder to prioritize and measure.",
    recommendedFirstAction: "Create a campaign with a single objective and primary channel before generating content.",
    estimatedTime: "2-4 minutes",
    quickStartSteps: [
      { id: "campaigns-start-1", title: "Create a campaign plan", description: "Enter a campaign name, objective, start date, and budget.", targetSelector: '[data-help="campaign-create-form"]' },
      { id: "campaigns-start-2", title: "Save the plan", description: "Save the campaign so it can be reused in creation and review flows.", targetSelector: '[data-help="campaign-create-form"]' },
      { id: "campaigns-start-3", title: "Generate content", description: "Use the Create content action once the plan is saved.", targetSelector: '[data-help="campaign-list"]' },
    ],
    tips: [
      "A small focused campaign is easier to manage than a broad plan that mixes too many channels.",
      "You can save a plan without going to AI Studio if you are still planning.",
    ],
    terminology: terms("Workflow", "Approval", "Content Readiness"),
    commonQuestions: [
      { question: "Does a campaign publish anything by itself?", answer: "No. A campaign organizes the objective and handoff into content creation; publishing still happens later." },
      { question: "Why is this different from the dashboard?", answer: "The dashboard prioritizes action. Campaigns store the plan structure used to guide creation and scheduling." },
    ],
    relatedPages: [
      { label: "AI Studio", href: "/studio" },
      { label: "Content Library", href: "/content" },
    ],
    academyLessonId: "generate-first-plan",
  },
  {
    id: "analytics",
    route: "/analytics",
    title: "Analytics",
    shortDescription: "Open the current analytics dashboards and understand which performance views are available today.",
    purpose: "This page is the entry point to analytics dashboards such as Amazon Ads insights and future performance views.",
    whyItMatters: "Analytics tell you whether drafts and campaigns are improving outcomes, not just producing activity.",
    recommendedFirstAction: "Open the dashboard that matches the channel you need to evaluate today.",
    estimatedTime: "2-5 minutes",
    quickStartSteps: [
      { id: "analytics-start-1", title: "Review available dashboards", description: "Open the analytics index and see which views are available in the current build.", route: "/analytics" },
      { id: "analytics-start-2", title: "Choose a channel", description: "Use Amazon Ads insights when you need current sandbox-based ad reporting.", route: "/analytics/amazon-ads" },
      { id: "analytics-start-3", title: "Return to the dashboard", description: "Use what you learn here to act on score, confidence, and next-step guidance.", route: "/" },
    ],
    tips: [
      "Some analytics are still sandbox or read-only, so check the page messaging before assuming live campaign control.",
      "If metrics look thin, review Integrations and Data Coverage to see what is missing.",
    ],
    terminology: terms("Marketing Health", "AI Confidence", "ROAS", "ACOS", "CTR", "Conversion Rate", "Data Coverage"),
    commonQuestions: [
      { question: "Why is analytics sparse?", answer: "Current analytics depend on connected providers and available snapshots. If those are limited, the dashboards will be limited too." },
      { question: "Where do I check missing data?", answer: "Use the dashboard Data Coverage notice and the Integrations page to see what is missing or disconnected." },
    ],
    relatedPages: [
      { label: "Integrations", href: "/integrations" },
      { label: "Dashboard", href: "/" },
    ],
    academyLessonId: "understand-marketing-score",
  },
  {
    id: "integrations",
    route: "/integrations",
    title: "Integrations",
    shortDescription: "Review connection state, provider support level, and missing permissions for your channels and data sources.",
    purpose: "This page is the high-level operational view for TikTok, Amazon Ads, and future providers defined in the integration registry.",
    whyItMatters: "Connected channels raise confidence, improve recommendations, and enable publishing or analytics workflows.",
    recommendedFirstAction: "Open the provider card that shows the most urgent error, reconnect requirement, or missing setup.",
    estimatedTime: "3-6 minutes",
    quickStartSteps: [
      { id: "integrations-start-1", title: "Select a provider", description: "Use the provider cards to pick the channel you want to connect or troubleshoot.", targetSelector: '[data-help="integrations-provider-grid"]' },
      { id: "integrations-start-2", title: "Review permissions", description: "Read missing scopes or failure messages before reconnecting.", targetSelector: '[data-help="integrations-provider-card"]' },
      { id: "integrations-start-3", title: "Connect the account", description: "Open the provider settings page to finish OAuth or token work.", targetSelector: '[data-help="integrations-provider-card"]' },
      { id: "integrations-start-4", title: "Verify health", description: "Return here and confirm the provider health has improved.", targetSelector: '[data-help="integrations-provider-grid"]' },
    ],
    tips: [
      "Support level tells you whether the provider is live, partial, or honestly still coming soon.",
      "Recent failure messages are meant to help you decide whether to reconnect, wait, or contact support.",
    ],
    terminology: terms("Integration Health", "Connected Channel", "Data Coverage"),
    commonQuestions: [
      { question: "Why can I see Amazon Ads but not manage everything?", answer: "The system shows current provider truth. Some Amazon flows remain limited or read-only until the live adapter is fully available." },
      { question: "What should I fix first?", answer: "Focus on reconnect required, token expired, degraded, or missing-scope states before anything marked merely coming soon." },
    ],
    relatedPages: [
      { label: "TikTok Settings", href: "/settings/integrations/tiktok" },
      { label: "Amazon Ads Settings", href: "/settings/integrations/amazon-ads" },
      { label: "Dashboard", href: "/" },
    ],
    academyLessonId: "connect-first-channel",
  },
  {
    id: "tiktok-settings",
    route: "/settings/integrations/tiktok",
    title: "TikTok Settings",
    shortDescription: "Connect TikTok, verify permissions, and review beta-safe publish job status.",
    purpose: "This page manages the TikTok OAuth connection, token health, creator details, and recent publish jobs.",
    whyItMatters: "TikTok requires explicit permissions and health checks before content can move safely into provider handoff.",
    recommendedFirstAction: "Check the connection status and permission checklist before trying to upload or publish anything.",
    estimatedTime: "5-8 minutes",
    quickStartSteps: [
      { id: "tiktok-start-1", title: "Review connection status", description: "Confirm whether the provider is connected, expired, or needs reconnection.", route: "/settings/integrations/tiktok" },
      { id: "tiktok-start-2", title: "Review required permissions", description: "Look for missing scopes before you retry OAuth.", route: "/settings/integrations/tiktok" },
      { id: "tiktok-start-3", title: "Connect or reconnect", description: "Use the connect button if the account is not fully ready.", route: "/settings/integrations/tiktok" },
      { id: "tiktok-start-4", title: "Check recent jobs", description: "Review recent publish jobs if a previous upload did not finish as expected.", route: "/settings/integrations/tiktok" },
    ],
    tips: [
      "Draft or inbox delivery status can still require a final step in TikTok itself.",
      "If verified media is not ready, prepare assets before you attempt pull-from-URL delivery.",
    ],
    terminology: terms("Integration Health", "Approval Required", "Connected Channel"),
    commonQuestions: [
      { question: "Why is direct post locked?", answer: "The status and permission model can intentionally keep direct posting unavailable until the provider confirms it is safe." },
      { question: "What does token health mean?", answer: "It tells you whether TikTok access is current, expiring, expired, or otherwise not ready for reliable use." },
    ],
    relatedPages: [
      { label: "Integrations", href: "/integrations" },
      { label: "Publishing Queue", href: "/publishing-queue" },
    ],
    academyLessonId: "connect-tiktok",
  },
  {
    id: "amazon-ads-settings",
    route: "/settings/integrations/amazon-ads",
    title: "Amazon Ads Settings",
    shortDescription: "Review the current Amazon Ads connection surface and current availability for sandbox or live workflows.",
    purpose: "This page is the Amazon Ads management entry point and should be treated as truthful about current capabilities.",
    whyItMatters: "Amazon performance and recommendations can influence campaign direction, but only where connected data really exists.",
    recommendedFirstAction: "Review the current status and then open the matching analytics or integration surface for deeper detail.",
    estimatedTime: "3-5 minutes",
    quickStartSteps: [
      { id: "amazon-start-1", title: "Open Amazon settings", description: "Review the current connection state and messaging.", route: "/settings/integrations/amazon-ads" },
      { id: "amazon-start-2", title: "Open Amazon analytics", description: "Use the current Amazon Ads analytics route for read-only insight review.", route: "/analytics/amazon-ads" },
      { id: "amazon-start-3", title: "Review provider truth", description: "Treat unsupported or partial status as current truth, not a hidden live capability.", route: "/integrations" },
    ],
    tips: [
      "If the page says sandbox or limited, assume that is the real state today.",
      "Use Help & Academy for the current walkthrough instead of guessing at unsupported flows.",
    ],
    terminology: terms("Integration Health", "ROAS", "ACOS", "CTR", "Conversion Rate"),
    commonQuestions: [
      { question: "Is Amazon Ads fully live here?", answer: "Only the implemented connection and reporting flows are available. Unsupported features are intentionally treated as coming soon." },
      { question: "Where do I see recommendations?", answer: "Use the Amazon Ads analytics or recommendations surfaces that are already implemented and clearly labeled." },
    ],
    relatedPages: [
      { label: "Integrations", href: "/integrations" },
      { label: "Analytics", href: "/analytics" },
    ],
    academyLessonId: "connect-amazon-ads",
    comingSoon: ["Full live Amazon Ads connection persistence remains limited to current implemented provider support."],
  },
  {
    id: "business-setup",
    route: "/onboarding",
    title: "Business Setup",
    shortDescription: "Set the business profile, audience, goals, and compliance mode used by every downstream recommendation.",
    purpose: "This page saves the workspace foundation that powers brand voice, safer content guidance, and better planning.",
    whyItMatters: "If setup is incomplete, almost every later page becomes less accurate or harder to trust.",
    recommendedFirstAction: "Complete the business profile and choose the correct industry before you start generating content.",
    estimatedTime: "5-8 minutes",
    quickStartSteps: [
      { id: "setup-start-1", title: "Complete business profile", description: "Add business name, website, goal, audience, and brand voice.", route: "/onboarding" },
      { id: "setup-start-2", title: "Choose industry and compliance mode", description: "Pick the best-fit industry so claim guardrails and channel guidance stay realistic.", route: "/onboarding" },
      { id: "setup-start-3", title: "Save and continue", description: "Save the setup before moving into AI Studio or integrations.", route: "/onboarding" },
    ],
    tips: [
      "Restricted industries get safer content guidance automatically after you save the right category.",
      "If you are just exploring, the demo path still uses the same structural setup logic.",
    ],
    terminology: terms("Compliance Mode", "Marketing Memory"),
    commonQuestions: [
      { question: "Why does this page matter so much?", answer: "This is the foundation for voice, guidance, and safety checks across the platform." },
      { question: "Can I change this later?", answer: "Yes. Update the profile as the business evolves so future plans and drafts stay aligned." },
    ],
    relatedPages: [
      { label: "Media Library", href: "/media" },
      { label: "Integrations", href: "/integrations" },
    ],
    academyLessonId: "complete-business-setup",
  },
  {
    id: "pricing",
    route: "/pricing",
    title: "Pricing",
    shortDescription: "Review available plans and choose the subscription level that fits your workspace needs.",
    purpose: "This page presents plan options and the next step into secure checkout.",
    whyItMatters: "Plan and credit readiness determine how smoothly your team can scale content and publishing workflows.",
    recommendedFirstAction: "Compare plan tiers and confirm the right fit for your expected usage.",
    estimatedTime: "2-4 minutes",
    quickStartSteps: [
      { id: "pricing-start-1", title: "Review plan options", description: "Compare available plan tiers and included capabilities.", route: "/pricing" },
      { id: "pricing-start-2", title: "Confirm billing readiness", description: "Check billing settings before final checkout decisions.", route: "/settings/billing" },
      { id: "pricing-start-3", title: "Continue to billing", description: "Open Billing Settings to manage subscription and invoices.", route: "/settings/billing" },
    ],
    tips: [
      "Use Billing Settings for invoice and credit visibility.",
      "If plan data is limited, keep your current setup and retry later.",
    ],
    terminology: terms("Credits", "AI Credits", "Video Credits"),
    commonQuestions: [
      { question: "Where do I manage invoices?", answer: "Open Billing Settings for invoice history and plan details." },
      { question: "How do credits relate to plans?", answer: "Plans define included capabilities, while credits track available usage." },
    ],
    relatedPages: [
      { label: "Billing Settings", href: "/settings/billing" },
      { label: "Help Center", href: "/help" },
    ],
    academyLessonId: "manage-credits-and-billing",
  },
  {
    id: "billing",
    route: "/settings/billing",
    title: "Billing",
    shortDescription: "Review subscription, invoices, and credit balances for AI, video, publishing, and analytics work.",
    purpose: "This page combines plan status, invoice visibility, and Stripe-powered checkout or portal handoff.",
    whyItMatters: "Billing readiness prevents blocked usage when your workspace starts depending on AI, video, or publishing volume.",
    recommendedFirstAction: "Review the current plan and confirm your available credits before you change anything.",
    estimatedTime: "3-5 minutes",
    quickStartSteps: [
      { id: "billing-start-1", title: "Review current plan", description: "Check the plan name and status at the top of the page.", targetSelector: '[data-help="billing-summary"]' },
      { id: "billing-start-2", title: "Check credit usage", description: "Review AI, video, publish, and analytics credit balances.", targetSelector: '[data-help="billing-summary"]' },
      { id: "billing-start-3", title: "Update billing info", description: "Use the Stripe billing portal if you need payment method changes.", targetSelector: '[data-help="billing-plan-grid"]' },
      { id: "billing-start-4", title: "Change plans", description: "Use checkout only when you are ready to move to a different tier.", targetSelector: '[data-help="billing-plan-grid"]' },
    ],
    tips: [
      "Credits and plan status are different: a workspace can have an active plan and still need more credits later.",
      "Billing review can be marked complete once you confirm plan and invoice readiness.",
    ],
    terminology: terms("Credits", "AI Credits", "Video Credits"),
    commonQuestions: [
      { question: "How do credits work?", answer: "Credits track available usage pools for AI, video, publishing, and analytics actions. The page shows each balance separately." },
      { question: "Can I change payment info here?", answer: "Yes, by opening the Stripe billing portal from this page." },
    ],
    relatedPages: [
      { label: "Branding Settings", href: "/settings/branding" },
      { label: "Dashboard", href: "/" },
    ],
    academyLessonId: "manage-credits-and-billing",
  },
  {
    id: "branding",
    route: "/settings/branding",
    title: "Branding Settings",
    shortDescription: "Set logo, color, domain, and login messaging for your workspace's branded experience.",
    purpose: "This page stores white-label-style branding fields already supported by the workspace settings layer.",
    whyItMatters: "Brand settings help content and workspace surfaces stay recognizable to the team and to customers.",
    recommendedFirstAction: "Upload or paste the logo URL and set the primary color before wider workspace rollout.",
    estimatedTime: "3-6 minutes",
    quickStartSteps: [
      { id: "branding-start-1", title: "Add the logo URL", description: "Use a stable logo asset URL that your team expects to reuse.", route: "/settings/branding" },
      { id: "branding-start-2", title: "Set the primary color", description: "Align the workspace with your main brand color.", route: "/settings/branding" },
      { id: "branding-start-3", title: "Add login messaging", description: "Use a headline that makes the branded entry experience clear to users.", route: "/settings/branding" },
    ],
    tips: [
      "If domain verification is still pending, you can still save the branding record without changing login behavior.",
      "Branding settings work best when the matching assets already exist in Media Library.",
    ],
    terminology: terms("Compliance Mode"),
    commonQuestions: [
      { question: "Will this change the whole app instantly?", answer: "These settings save the branded values, but some operational steps like DNS verification may still be staged separately." },
      { question: "Where should my logo come from?", answer: "Use a stable hosted asset, ideally one already stored and approved in your Media Library." },
    ],
    relatedPages: [
      { label: "Media Library", href: "/media" },
      { label: "Account Settings", href: "/settings/account" },
    ],
    academyLessonId: "upload-brand-assets",
  },
  {
    id: "director-settings",
    route: "/settings/marketing-director",
    title: "Marketing Director Settings",
    shortDescription: "Configure operating mode, autonomy level, approvals, and daily brief behavior for the Marketing Director.",
    purpose: "This page controls how strongly the platform can assist and which approval checkpoints remain active.",
    whyItMatters: "These settings directly affect safety, execution behavior, and whether recommendations can move forward autonomously.",
    recommendedFirstAction: "Confirm the operating mode and approval requirements before enabling more automated workflows.",
    estimatedTime: "4-6 minutes",
    quickStartSteps: [
      { id: "director-settings-1", title: "Review mode", description: "Choose Advisor, Copilot, or Autopilot based on your current risk tolerance.", route: "/settings/marketing-director" },
      { id: "director-settings-2", title: "Check approvals", description: "Keep required approvals aligned with how much autonomy you want.", route: "/settings/marketing-director" },
      { id: "director-settings-3", title: "Set daily brief timing", description: "Choose when the brief should be ready for your team.", route: "/settings/marketing-director" },
    ],
    tips: [
      "Advisor mode is the safest entry point for new teams or early beta testing.",
      "Autonomy level and approval rules work together. Do not interpret one without the other.",
    ],
    terminology: terms("Advisor Mode", "Copilot Mode", "Autopilot", "Approval Required"),
    commonQuestions: [
      { question: "Can Autopilot bypass approvals?", answer: "No. Existing approval settings and safety rules still apply." },
      { question: "What should beta teams use first?", answer: "Start with Advisor or a balanced Copilot setup until the workflow is familiar." },
    ],
    relatedPages: [
      { label: "Dashboard", href: "/" },
      { label: "Approval Center", href: "/approvals" },
    ],
    academyLessonId: "use-advisor-mode-safely",
  },
  {
    id: "approval-center",
    route: "/approvals",
    title: "Approval Center",
    shortDescription: "Review approval items that are blocking content, campaigns, recommendations, or publishing work.",
    purpose: "This page gathers approval records from the current workspace so reviewers can see what is pending and what was already resolved.",
    whyItMatters: "Approvals are where safe execution either moves forward or stops. A stuck queue delays publishing and weakens workflow trust.",
    recommendedFirstAction: "Filter to pending items and resolve the oldest blocker first.",
    estimatedTime: "2-5 minutes",
    quickStartSteps: [
      { id: "approvals-start-1", title: "Open pending items", description: "Start with items still waiting for a decision.", targetSelector: '[data-help="approvals-list"]' },
      { id: "approvals-start-2", title: "Review context", description: "Check type, title, and any related record before you approve or reject.", targetSelector: '[data-help="approvals-list"]' },
      { id: "approvals-start-3", title: "Move the workflow forward", description: "After approval, continue into the calendar or publishing queue if needed.", route: "/publishing-queue" },
    ],
    tips: [
      "Approvals are not the same as drafts. This page is the reviewer view across workflow items.",
      "If the same blocker keeps returning, check Marketing Director settings and the command context that created it.",
    ],
    terminology: terms("Approval", "Workflow", "Approval Required"),
    commonQuestions: [
      { question: "Why is an item here if the content already exists?", answer: "Content creation and approval are separate states. A saved draft can still need a human decision." },
      { question: "Where do approved items go next?", answer: "That depends on the workflow, but common next stops are the calendar, publishing queue, or a related content record." },
    ],
    relatedPages: [
      { label: "Content Library", href: "/content" },
      { label: "Publishing Queue", href: "/publishing-queue" },
      { label: "Marketing Director Settings", href: "/settings/marketing-director" },
    ],
    academyLessonId: "review-and-approve-content",
  },
  {
    id: "publishing-queue",
    route: "/publishing-queue",
    title: "Publishing Queue",
    shortDescription: "Track items that are queued, preparing, publishing, retrying, or failed after leaving the calendar.",
    purpose: "This page focuses on execution state rather than planning state, using scheduled post status and publishing workflow helpers.",
    whyItMatters: "A clean queue keeps content flowing on time and surfaces failed or blocked items before they become missed posts.",
    recommendedFirstAction: "Review failed or retrying items first, then check anything still stuck in preparation.",
    estimatedTime: "2-4 minutes",
    quickStartSteps: [
      { id: "queue-start-1", title: "Review current execution stages", description: "Check which posts are queued, preparing, publishing, or failed.", route: "/publishing-queue" },
      { id: "queue-start-2", title: "Open failed items", description: "Investigate failures before adding more posts to the queue.", route: "/publishing-queue" },
      { id: "queue-start-3", title: "Return to calendar", description: "If the timing or channel needs to change, go back to Calendar.", route: "/calendar" },
    ],
    tips: [
      "This page is the best place to explain missed publishing, not the campaign plan page.",
      "A retry state usually means the item is still recoverable without recreating the draft.",
    ],
    terminology: terms("Publishing Queue", "Scheduled", "Workflow"),
    commonQuestions: [
      { question: "Why can’t I publish?", answer: "Check for approval blockers, disconnected integrations, or failed queue stages on this page and on Integrations." },
      { question: "What is the difference between Calendar and Queue?", answer: "Calendar is planning and assignment. Queue is real execution progress after the post is handed off." },
    ],
    relatedPages: [
      { label: "Publishing Calendar", href: "/calendar" },
      { label: "Integrations", href: "/integrations" },
      { label: "Notifications", href: "/notifications" },
    ],
  },
  {
    id: "notifications",
    route: "/notifications",
    title: "Notifications",
    shortDescription: "See workspace notifications for approvals, failures, and major workflow events.",
    purpose: "This page summarizes the marketing notification records already created by workflow and execution logic.",
    whyItMatters: "Notifications help users understand what changed without constantly refreshing multiple operational pages.",
    recommendedFirstAction: "Review pending notifications first, especially anything related to approvals or publishing failures.",
    estimatedTime: "1-3 minutes",
    quickStartSteps: [
      { id: "notifications-start-1", title: "Open pending notifications", description: "Focus on unread or pending items that require action.", route: "/notifications" },
      { id: "notifications-start-2", title: "Open the linked workflow page", description: "Use the event type to decide whether to open approvals, publishing, or the dashboard.", route: "/notifications" },
    ],
    tips: [
      "Notifications explain what happened; the action still happens on the owning page.",
      "Repeated notification failures usually point back to the workflow, not to this screen itself.",
    ],
    terminology: terms("Approval", "Workflow", "Publishing Queue"),
    commonQuestions: [
      { question: "Can I clear notifications here?", answer: "The current Monday slice focuses on review and understanding. Management actions remain intentionally light." },
      { question: "Why do I have notifications but no failed post?", answer: "Some notifications describe approvals, opportunities, or analytics availability rather than publishing errors." },
    ],
    relatedPages: [
      { label: "Dashboard", href: "/" },
      { label: "Approval Center", href: "/approvals" },
      { label: "Publishing Queue", href: "/publishing-queue" },
    ],
    comingSoon: ["Advanced bulk notification management is still coming soon."],
  },
  {
    id: "team-settings",
    route: "/settings/team",
    title: "Team Settings",
    shortDescription: "Review roles, invitations, and collaboration guidance for the current workspace.",
    purpose: "This page is the workspace team guidance surface for role-aware collaboration, invitations, and approvals.",
    whyItMatters: "Clear ownership prevents approval bottlenecks and helps the right people see the right work.",
    recommendedFirstAction: "Review active members and role expectations before inviting new users.",
    estimatedTime: "3-5 minutes",
    quickStartSteps: [
      { id: "team-start-1", title: "Review current team", description: "See who is already active in the workspace.", route: "/settings/team" },
      { id: "team-start-2", title: "Check role expectations", description: "Match roles to the approvals and publishing responsibility you expect.", route: "/settings/team" },
      { id: "team-start-3", title: "Use invitations carefully", description: "Invite only the people who need access to current workspace workflows.", route: "/settings/team" },
    ],
    tips: [
      "Roles affect what users can approve, schedule, or manage.",
      "Keep role expansion narrow during Monday beta testing.",
    ],
    terminology: terms("Approval Required", "Workflow"),
    commonQuestions: [
      { question: "Can this page manage every membership action?", answer: "The Monday slice focuses on visibility and guidance built on the current workspace membership model." },
      { question: "Where do admin-only membership actions live?", answer: "Super-admin level account operations still live in the admin console." },
    ],
    relatedPages: [
      { label: "Account Settings", href: "/settings/account" },
      { label: "Marketing Director Settings", href: "/settings/marketing-director" },
    ],
    comingSoon: ["Expanded self-serve team management flows remain limited in the current build."],
  },
  {
    id: "products",
    route: "/products",
    title: "Products and Product Setup",
    shortDescription: "Review product-data readiness and understand how product coverage affects recommendations.",
    purpose: "This page explains current product support, checks whether the products table exists, and points users to the next safe step.",
    whyItMatters: "Product context improves campaign ideas, creative direction, and data coverage, especially for commerce workflows.",
    recommendedFirstAction: "Check whether product records are available in this environment before you expect product-aware AI output.",
    estimatedTime: "2-4 minutes",
    quickStartSteps: [
      { id: "products-start-1", title: "Review product readiness", description: "Check whether the current workspace has product catalog support available.", route: "/products" },
      { id: "products-start-2", title: "Understand the impact", description: "Use the explanation on this page to see how missing products change planning confidence.", route: "/products" },
      { id: "products-start-3", title: "Return to campaigns or AI Studio", description: "Once product data exists, use it to create more specific content.", route: "/studio" },
    ],
    tips: [
      "If the environment does not expose a products table, treat product-aware workflows as limited rather than assumed.",
      "Product setup matters most when you want specific product-led messaging or offers.",
    ],
    terminology: terms("Data Coverage", "AI Confidence"),
    commonQuestions: [
      { question: "Where do I add products?", answer: "This page tells you whether the current environment supports product records directly. If not, product-aware guidance stays limited instead of pretending the feature exists." },
      { question: "Why does product setup affect the dashboard?", answer: "Missing product data lowers context quality for recommendations and content targeting." },
    ],
    relatedPages: [
      { label: "Campaigns", href: "/marketing/campaigns" },
      { label: "AI Studio", href: "/studio" },
      { label: "Dashboard", href: "/" },
    ],
    comingSoon: ["Full in-app product catalog management may depend on the environment and is not guaranteed in the Monday slice."],
  },
  {
    id: "video-studio",
    route: "/studio",
    title: "AI Marketing Studio",
    shortDescription: "Generate marketing content and video ideas using your campaign context, assets, and current workspace setup.",
    purpose: "This page is the creation surface where planning turns into actual drafts, prompts, and creative output.",
    whyItMatters: "It is the fastest path from idea to draft, but it works best when setup, media, and campaigns are already in place.",
    recommendedFirstAction: "Start with a specific objective, channel, and asset set instead of a vague prompt.",
    estimatedTime: "5-10 minutes",
    quickStartSteps: [
      { id: "studio-start-1", title: "Bring campaign context", description: "Use a campaign or dashboard recommendation as the source of truth for the request.", route: "/marketing/campaigns" },
      { id: "studio-start-2", title: "Create the first draft", description: "Generate content or video direction based on the goal and channel.", route: "/studio" },
      { id: "studio-start-3", title: "Save to the library", description: "Move usable content into the Content Library for review.", route: "/content" },
    ],
    tips: [
      "Specific inputs usually produce safer and more reusable drafts.",
      "If feedback says the output is weak, check missing assets or incomplete setup before trying a more complex prompt.",
    ],
    terminology: terms("AI Credits", "Video Credits", "Content Readiness"),
    commonQuestions: [
      { question: "Why does the studio still ask me to review content later?", answer: "Generation is not the same as approval. Review and scheduling remain separate safety steps." },
      { question: "What helps the studio most?", answer: "A saved workspace profile, uploaded media, connected channels, and a clear campaign objective." },
    ],
    relatedPages: [
      { label: "Content Library", href: "/content" },
      { label: "Media Library", href: "/media" },
      { label: "Campaigns", href: "/marketing/campaigns" },
    ],
    academyLessonId: "generate-content-from-plan",
  },
  {
    id: "account-settings",
    route: "/settings/account",
    title: "Account Settings",
    shortDescription: "Manage personal guidance preferences, help mode, and account-level assistance settings.",
    purpose: "This page is the main user-facing settings surface for help mode, trainer behavior, and learning progress entry points.",
    whyItMatters: "It gives users control over how much guidance the product shows without changing core workflows.",
    recommendedFirstAction: "Set Help Mode to the level that matches your familiarity with the platform.",
    estimatedTime: "1-3 minutes",
    quickStartSteps: [
      { id: "account-start-1", title: "Choose Help Mode", description: "Pick ON, OFF, or AUTO based on how much guidance you want.", route: "/settings/account" },
      { id: "account-start-2", title: "Review trainer prompts", description: "Leave proactive trainer prompts on unless they interrupt your workflow.", route: "/settings/account" },
      { id: "account-start-3", title: "Open Help Center or Academy", description: "Use the linked resources to learn more without leaving the app.", route: "/help" },
    ],
    tips: [
      "AUTO is usually best for Monday beta testers because it reduces noise after repeat visits.",
      "Help Mode OFF hides nonessential guidance but does not remove primary workflow actions.",
    ],
    terminology: terms("Advisor Mode", "AI Confidence"),
    commonQuestions: [
      { question: "What does AUTO do?", answer: "AUTO shows more help on new or confusing pages, then reduces it after repeat success and familiarity." },
      { question: "Will Help Mode change my permissions?", answer: "No. It only changes how much instructional UI is shown." },
    ],
    relatedPages: [
      { label: "Help Center", href: "/help" },
      { label: "Academy", href: "/academy" },
      { label: "Team Settings", href: "/settings/team" },
    ],
  },
  {
    id: "knowledge-base",
    route: "/knowledge",
    title: "Knowledge Base",
    shortDescription: "Review winning content examples and signals that can teach future drafts what performs well.",
    purpose: "This page stores approved knowledge items derived from content and performance snapshots.",
    whyItMatters: "Knowledge makes future AI guidance less generic by grounding it in your own results.",
    recommendedFirstAction: "Open a winning item and review why it was strong enough to teach future content.",
    estimatedTime: "2-4 minutes",
    quickStartSteps: [
      { id: "knowledge-start-1", title: "Review saved knowledge", description: "See which posts were promoted into the knowledge base.", route: "/knowledge" },
      { id: "knowledge-start-2", title: "Compare with performance", description: "Use the attached results to understand why the item was saved.", route: "/calendar" },
    ],
    tips: [
      "Only stronger approved results should be promoted into knowledge.",
      "The knowledge base supports learning, not automatic publishing.",
    ],
    terminology: terms("Marketing Memory", "AI Confidence"),
    commonQuestions: [
      { question: "Can every post enter the knowledge base?", answer: "No. The current flow expects stronger scores and confidence before a result becomes reusable learning." },
      { question: "Why does this matter for new drafts?", answer: "It gives future AI generation more grounded examples from your own workspace." },
    ],
    relatedPages: [
      { label: "Publishing Calendar", href: "/calendar" },
      { label: "Dashboard", href: "/" },
    ],
  },
  {
    id: "admin-overview",
    route: "/admin",
    title: "Admin Console",
    shortDescription: "See customer, revenue, usage, and operational health across the platform.",
    purpose: "This page is the top-level super-admin overview for accounts, users, revenue, usage, and system signals.",
    whyItMatters: "It gives operators one place to spot launch risk before digging into feature, billing, or audit details.",
    recommendedFirstAction: "Review health and failed-payment signals before making operational changes.",
    quickStartSteps: [
      { id: "admin-start-1", title: "Review metrics", description: "Check accounts, revenue, usage, and system health summaries.", route: "/admin" },
      { id: "admin-start-2", title: "Inspect the operational risk area", description: "Use recent errors and audit trail sections to understand current issues.", route: "/admin" },
    ],
    tips: ["Admin guidance is intentionally concise because super-admin workflows should not auto-interrupt by default."],
    terminology: terms("Marketing Health", "AI Confidence"),
    commonQuestions: [{ question: "Should the AI Trainer interrupt admins?", answer: "No. Proactive prompts stay disabled for super-admin workflows unless deliberately enabled." }],
    relatedPages: [
      { label: "Admin Integrations", href: "/admin/integrations" },
      { label: "Admin Operations", href: "/admin/operations" },
      { label: "Admin Audit", href: "/admin/audit" },
    ],
    audience: "admin",
  },
  {
    id: "admin-integrations",
    route: "/admin/integrations",
    title: "Admin Integrations",
    shortDescription: "Control global provider state, maintenance mode, and failed job recovery actions.",
    purpose: "This page manages provider-level operations rather than customer-facing connection setup.",
    whyItMatters: "A provider outage or maintenance mode can affect many workspaces at once.",
    recommendedFirstAction: "Review failed jobs and provider controls before enabling or disabling anything.",
    quickStartSteps: [
      { id: "admin-integrations-1", title: "Review provider state", description: "Check whether a provider is intentionally paused, degraded, or healthy.", route: "/admin/integrations" },
      { id: "admin-integrations-2", title: "Inspect failed jobs", description: "Only requeue jobs after the underlying provider problem is understood.", route: "/admin/integrations" },
    ],
    tips: ["This page is operational truth, not a place to mask provider limitations."],
    terminology: terms("Integration Health", "Workflow"),
    commonQuestions: [{ question: "Why does customer-facing status differ from admin controls?", answer: "Customer pages show workspace experience. Admin pages show platform-level operational state and controls." }],
    relatedPages: [{ label: "Admin Operations", href: "/admin/operations" }],
    audience: "admin",
  },
  {
    id: "admin-operations",
    route: "/admin/operations",
    title: "Admin Operations",
    shortDescription: "Track monitoring snapshots, backup runs, replay operations, and support load.",
    purpose: "This page is the launch-readiness control room for operational visibility.",
    whyItMatters: "Backup, restore, replay, and support indicators tell you whether the platform is ready for customer traffic and recovery work.",
    recommendedFirstAction: "Review the latest monitoring snapshot and any open support or replay activity.",
    quickStartSteps: [
      { id: "admin-operations-1", title: "Check monitoring", description: "Review server health, queue depth, and failure signals.", route: "/admin/operations" },
      { id: "admin-operations-2", title: "Review recovery posture", description: "Look at backup, restore, and replay records before beta testing starts.", route: "/admin/operations" },
    ],
    tips: ["An empty restore history is a risk signal, not a clean bill of health."],
    terminology: terms("Marketing Health", "Workflow"),
    commonQuestions: [{ question: "What should I check before Monday?", answer: "Monitoring, support backlog, replay activity, and any failed recovery signals deserve the first pass." }],
    relatedPages: [{ label: "Admin Console", href: "/admin" }],
    audience: "admin",
  },
  {
    id: "admin-costs",
    route: "/admin/costs",
    title: "Admin AI Costs",
    shortDescription: "Inspect AI usage cost, revenue allocation, refunds, and rate gaps.",
    purpose: "This page is the platform-level cost center for tracked AI usage events.",
    whyItMatters: "Beta usage can rise quickly, so cost visibility helps operators catch unpriced or unexpected AI activity.",
    recommendedFirstAction: "Check missing rate gaps and unusual cost spikes before you dive into individual events.",
    quickStartSteps: [
      { id: "admin-costs-1", title: "Review cost summary", description: "Use the top metrics to understand total cost, margin, and refunds.", route: "/admin/costs" },
      { id: "admin-costs-2", title: "Filter the event table", description: "Narrow by provider, model, feature, or account when something looks wrong.", route: "/admin/costs" },
    ],
    tips: ["A missing rate gap means the platform saw the event but cannot price it reliably yet."],
    terminology: terms("AI Credits", "Video Credits"),
    commonQuestions: [{ question: "Why does a cost row say rate not configured?", answer: "The usage event exists, but the pricing rate needed for a reliable actual-cost calculation is still missing." }],
    relatedPages: [{ label: "Admin Console", href: "/admin" }],
    audience: "admin",
  },
  {
    id: "admin-settings",
    route: "/admin/settings",
    title: "Admin Settings",
    shortDescription: "Review controlled system settings and operational configuration values.",
    purpose: "This page is the guarded surface for system-level settings that affect the platform globally.",
    whyItMatters: "System settings can change cross-workspace behavior, so they need careful, auditable handling.",
    recommendedFirstAction: "Review the setting category and description before editing any value.",
    quickStartSteps: [
      { id: "admin-settings-1", title: "Inspect category", description: "Make sure you are editing the right global setting group.", route: "/admin/settings" },
      { id: "admin-settings-2", title: "Check for audit impact", description: "Use the audit log if you need to understand recent sensitive changes.", route: "/admin/audit" },
    ],
    tips: ["Never use this page to guess at missing configuration; verify the intended value first."],
    terminology: terms("Workflow"),
    commonQuestions: [{ question: "Can user help preferences be changed here?", answer: "No. User-scoped help preferences live with the user account, not in global admin settings." }],
    relatedPages: [{ label: "Admin Audit", href: "/admin/audit" }],
    audience: "admin",
  },
  {
    id: "admin-audit",
    route: "/admin/audit",
    title: "Admin Audit Log",
    shortDescription: "Review sensitive system and admin actions with reasons and timestamps.",
    purpose: "This page shows audit records for privileged or sensitive operational actions.",
    whyItMatters: "It is the source of truth for who changed what and why during beta operations.",
    recommendedFirstAction: "Review the newest entries after any sensitive account, settings, or provider action.",
    quickStartSteps: [
      { id: "admin-audit-1", title: "Read the newest actions", description: "Start at the most recent audit records to understand what changed.", route: "/admin/audit" },
      { id: "admin-audit-2", title: "Correlate with operations", description: "Use the audit log alongside admin operations and integrations pages when troubleshooting.", route: "/admin/operations" },
    ],
    tips: ["A missing reason on a sensitive action should be treated as an operational smell."],
    terminology: terms("Workflow"),
    commonQuestions: [{ question: "When should I check audit first?", answer: "Whenever settings, membership, or provider behavior changed recently and you need a trusted history." }],
    relatedPages: [{ label: "Admin Console", href: "/admin" }],
    audience: "admin",
  },
];

export function normalizeHelpRoute(route: string): string {
  if (!route) return "/";
  const cleaned = route.split("?")[0]?.replace(/\/$/, "") || "/";
  return cleaned || "/";
}

export function getPageHelp(route: string): PageHelpEntry | null {
  const normalized = normalizeHelpRoute(route);
  return PAGE_HELP_REGISTRY.find((entry) => normalizeHelpRoute(entry.route) === normalized) || null;
}

export const PRIMARY_HELP_ROUTES = PAGE_HELP_REGISTRY.map((entry) => entry.route);
