import type { AmazonAdsInsightRecord } from "@/features/marketing/providers/amazon-ads/insights/types";

// Deterministic sandbox fixture for dashboard rendering and tests.
export const AMAZON_ADS_INSIGHT_FIXTURE: AmazonAdsInsightRecord[] = [
  {
    workspaceId: "workspace-sandbox-01",
    providerId: "amazon-ads-sandbox",
    campaignId: "sp-001",
    campaignName: "SP | Dog Treats Core",
    campaignType: "SPONSORED_PRODUCTS",
    campaignStatus: "ENABLED",
    budget: 50,
    keywordId: "kw-001",
    keyword: "freeze dried dog treats",
    matchType: "EXACT",
    searchTerm: "freeze dried dog treats",
    marketplaceId: "US",
    profileId: "profile-us-001",
    date: "2026-03-01",
    impressions: 1200,
    clicks: 96,
    spend: 82.4,
    sales: 410,
    orders: 17,
  },
  {
    workspaceId: "workspace-sandbox-01",
    providerId: "amazon-ads-sandbox",
    campaignId: "sp-001",
    campaignName: "SP | Dog Treats Core",
    campaignType: "SPONSORED_PRODUCTS",
    campaignStatus: "ENABLED",
    budget: 50,
    keywordId: "kw-002",
    keyword: "single ingredient dog treats",
    matchType: "PHRASE",
    searchTerm: "single ingredient dog treats",
    marketplaceId: "US",
    profileId: "profile-us-001",
    date: "2026-03-02",
    impressions: 900,
    clicks: 62,
    spend: 54.35,
    sales: 220,
    orders: 9,
  },
  {
    workspaceId: "workspace-sandbox-01",
    providerId: "amazon-ads-sandbox",
    campaignId: "sb-010",
    campaignName: "SB | Bite Me Brand",
    campaignType: "SPONSORED_BRANDS",
    campaignStatus: "PAUSED",
    budget: 35,
    keywordId: "kw-101",
    keyword: "bite me dog snacks",
    matchType: "BROAD",
    searchTerm: "bite me dog snacks",
    marketplaceId: "US",
    profileId: "profile-us-001",
    date: "2026-03-02",
    impressions: 600,
    clicks: 28,
    spend: 26.9,
    sales: 75,
    orders: 3,
  },
  {
    workspaceId: "workspace-sandbox-01",
    providerId: "amazon-ads-sandbox",
    campaignId: "sd-042",
    campaignName: "SD | Competitor Defense",
    campaignType: "SPONSORED_DISPLAY",
    campaignStatus: "ENABLED",
    budget: 40,
    keywordId: "kw-201",
    keyword: "healthy dog jerky",
    matchType: "EXACT",
    searchTerm: "healthy dog jerky",
    marketplaceId: "CA",
    profileId: "profile-ca-001",
    date: "2026-03-03",
    impressions: 700,
    clicks: 41,
    spend: 33.1,
    sales: 132,
    orders: 6,
  },
  {
    workspaceId: "workspace-sandbox-01",
    providerId: "amazon-ads-sandbox",
    campaignId: "sd-042",
    campaignName: "SD | Competitor Defense",
    campaignType: "SPONSORED_DISPLAY",
    campaignStatus: "ENABLED",
    budget: 40,
    keywordId: "kw-202",
    keyword: "beef dog treats",
    matchType: "PHRASE",
    searchTerm: "beef dog treats",
    marketplaceId: "CA",
    profileId: "profile-ca-001",
    date: "2026-03-04",
    impressions: 680,
    clicks: 38,
    spend: 30.4,
    sales: 148,
    orders: 7,
  },
];
