export const KNOWLEDGE_ENGINE_CONFIG = {
  maxFileSizeBytes: Number(process.env.KNOWLEDGE_MAX_FILE_SIZE_BYTES || 20 * 1024 * 1024),
  maxExtractedCharacters: Number(process.env.KNOWLEDGE_MAX_EXTRACTED_CHARACTERS || 300_000),
  maxUploadFilenameLength: Number(process.env.KNOWLEDGE_MAX_FILENAME_LENGTH || 180),
  maxSnippetLength: Number(process.env.KNOWLEDGE_MAX_SNIPPET_LENGTH || 280),
  maxCitationExcerptLength: Number(process.env.KNOWLEDGE_MAX_CITATION_EXCERPT_LENGTH || 320),
  localStorageRoot: process.env.KNOWLEDGE_LOCAL_STORAGE_ROOT || ".knowledge-storage",
  chunking: {
    targetChars: Number(process.env.KNOWLEDGE_CHUNK_TARGET_CHARS || 1400),
    maxChars: Number(process.env.KNOWLEDGE_CHUNK_MAX_CHARS || 1900),
    overlapChars: Number(process.env.KNOWLEDGE_CHUNK_OVERLAP_CHARS || 180),
    minChars: Number(process.env.KNOWLEDGE_CHUNK_MIN_CHARS || 280),
    preserveHeadings: true,
    preferPageBoundaries: true,
  },
  spreadsheet: {
    maxSheets: Number(process.env.KNOWLEDGE_XLSX_MAX_SHEETS || 20),
    maxRowsPerSheet: Number(process.env.KNOWLEDGE_XLSX_MAX_ROWS || 2000),
    maxCellsPerRow: Number(process.env.KNOWLEDGE_XLSX_MAX_CELLS_PER_ROW || 60),
  },
  presentation: {
    maxSlides: Number(process.env.KNOWLEDGE_PPTX_MAX_SLIDES || 250),
  },
  pdf: {
    maxPages: Number(process.env.KNOWLEDGE_PDF_MAX_PAGES || 300),
  },
  supportedMimeTypes: [
    "text/plain",
    "text/markdown",
    "text/csv",
    "application/pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "image/png",
    "image/jpeg",
    "image/webp",
  ] as const,
  supportedExtensions: ["txt", "md", "csv", "pdf", "docx", "pptx", "xlsx", "png", "jpg", "jpeg", "webp"] as const,
  blockedExtensions: ["exe", "bat", "cmd", "ps1", "sh", "js", "ts", "zip", "tar", "gz", "rar", "7z", "html", "htm"] as const,
  features: {
    connectors: {
      upload: true,
      website: false,
      googleDrive: false,
      dropbox: false,
      oneDrive: false,
      notion: false,
      github: false,
      rss: false,
    },
    vectorSearch: false,
    ocr: false,
    backgroundWorkers: false,
  },
} as const;
