import type { AmazonAdsRecommendationThresholds } from "@/features/marketing/providers/amazon-ads/recommendations/types";

export const AMAZON_ADS_RECOMMENDATION_THRESHOLDS: AmazonAdsRecommendationThresholds = {
  highSpendSearchTermMinSpend: 25,
  highSpendSearchTermMinClicks: 20,
  negativeKeywordMinSpend: 15,
  negativeKeywordMinClicks: 15,
  profitableTermMinOrders: 3,
  profitableTermMinRoas: 3,
  profitableTermMinClicks: 18,
  keywordHighAcosThreshold: 45,
  keywordHighAcosMinSpend: 20,
  keywordLowImpressionsThreshold: 500,
  keywordLowImpressionsMinClicks: 4,
  budgetLimitedSpendRatioThreshold: 0.9,
  budgetLimitedMinSpend: 20,
  campaignWastedSpendMinSpend: 30,
  campaignWastedSpendAcosThreshold: 70,
  budgetReallocationStrongRoasThreshold: 4,
  budgetReallocationWeakRoasThreshold: 1.8,
  budgetReallocationMinStrongSpend: 25,
  budgetReallocationMinWeakSpend: 25,
  bidIncreaseMinRoas: 4,
  bidIncreaseMinOrders: 4,
  bidIncreaseMinClicks: 25,
  bidDecreaseAcosThreshold: 60,
  bidDecreaseMinClicks: 20,
  bidDecreaseMinSpend: 20,
  decliningRoasMinDailyPoints: 4,
  decliningRoasDropPercentThreshold: 25,
  scaleCandidateMinRoas: 4,
  scaleCandidateMinOrders: 8,
  scaleCandidateMinSpend: 30,
};
